version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      "node.name": "es_presentation"
      "discovery.type": "single-node"
      "cluster.name": "presentation-cluster"


  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_GRAPH_ENABLED: "false"
      XPACK_ML_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_WATCHER_ENABLED: "false"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  data:
    driver: local
